[app]
address = "0.0.0.0"
port = 8080

[database]
name = "scoreplay"
username = "scoreplay"
password = "scoreplay"

[stripe]
key = "sk_test_oJglhpvVKdhXGKT3YGlw5Ems00a6aT2Iex"

[email]
email = "contact@scoreplay.io"
password = "Scoreplay2018"